"""empty message

Revision ID: 05124292fff6
Revises: beb35c0600dd
Create Date: 2024-08-07 03:14:20.552633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05124292fff6'
down_revision = 'beb35c0600dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yahoo_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('yahoo_id')

    op.drop_table('ebay_token')
    # ### end Alembic commands ###
