"""empty message

Revision ID: 0857ddae7997
Revises: 
Create Date: 2024-04-17 04:17:54.949710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0857ddae7997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('auction_id', sa.String(length=255), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('bitFirstAmount', sa.Integer(), nullable=True),
    sa.Column('maxAmount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
