"""empty message

Revision ID: 44405f008cea
Revises: cdc388983375
Create Date: 2024-04-26 07:42:47.321263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44405f008cea'
down_revision = 'cdc388983375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('product_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('bid_first_amount',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('max_amount',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('seconds',
               existing_type=mysql.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('seconds',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('max_amount',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bid_first_amount',
               existing_type=sa.Integer(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('close_time')

    # ### end Alembic commands ###
