"""empty message

Revision ID: beb35c0600dd
Revises: 9d5eccb4e08b
Create Date: 2024-08-07 03:00:08.845704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb35c0600dd'
down_revision = '9d5eccb4e08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yahoo_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('yahoo_id')

    # ### end Alembic commands ###
