"""empty message

Revision ID: cdc388983375
Revises: 65ffded39fbd
Create Date: 2024-04-26 06:19:35.250225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdc388983375'
down_revision = '65ffded39fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bid_first_amount', sa.Integer(), nullable=True, sort_order=6))
        batch_op.add_column(sa.Column('max_amount', sa.Integer(), nullable=True, sort_order=7))
        batch_op.add_column(sa.Column('seconds', sa.Integer(), nullable=True, sort_order=8))
        batch_op.drop_column('maxAmount')
        batch_op.drop_column('bitFirstAmount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bitFirstAmount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('maxAmount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('seconds')
        batch_op.drop_column('max_amount')
        batch_op.drop_column('bid_first_amount')

    # ### end Alembic commands ###
