"""empty message

Revision ID: d1dd95c67c79
Revises: 2afcd0a1f6e7
Create Date: 2024-06-21 00:51:49.276023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1dd95c67c79'
down_revision = '2afcd0a1f6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bid_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_succeeded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('is_succeeded')
        batch_op.drop_column('bid_time')
        batch_op.drop_column('is_processed')

    # ### end Alembic commands ###
